-- ============================================================================
-- Assignment 10: Car Rental & Vehicle Fleet Management Schema
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 3.1 Assignment schema (verbatim)
-- ----------------------------------------------------------------------------

-- 1. Vehicles Table
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand TEXT NOT NULL,
    model TEXT NOT NULL,
    year INT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Sedan', 'SUV', 'Luxury', 'Hatchback', 'Electric')),
    daily_rate NUMERIC(10, 2) NOT NULL CHECK (daily_rate > 0),
    fuel_type TEXT NOT NULL,
    seating_capacity INT NOT NULL DEFAULT 5,
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'rented', 'maintenance')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Rentals / Bookings Table
CREATE TABLE IF NOT EXISTS rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL, -- references Supabase auth.users
    vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE RESTRICT,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_cost NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'booked' CHECK (status IN ('booked', 'active', 'completed', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT valid_date_range CHECK (end_date >= start_date)
);

-- ----------------------------------------------------------------------------
-- 3.2 Extras: Indexes, btree_gist Exclusion Constraint, & RLS Policies
-- ----------------------------------------------------------------------------

-- Indexes for common queries and overlap checks
CREATE INDEX IF NOT EXISTS idx_rentals_user ON rentals(user_id);
CREATE INDEX IF NOT EXISTS idx_rentals_vehicle_dates ON rentals(vehicle_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_vehicles_category_status ON vehicles(category, status);

-- Database-level safety net against double-booking (race conditions):
-- Two active/booked rentals of the same vehicle can never have overlapping (inclusive) date ranges.
CREATE EXTENSION IF NOT EXISTS btree_gist;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'no_double_booking'
    ) THEN
        ALTER TABLE rentals ADD CONSTRAINT no_double_booking 
        EXCLUDE USING gist (
            vehicle_id WITH =, 
            daterange(start_date, end_date, '[]') WITH &&
        ) WHERE (status IN ('booked', 'active'));
    END IF;
END $$;

-- Row Level Security: the API talks to the DB through the server (service role);
-- direct client access is read-only.
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE rentals ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Vehicles are publicly readable' AND tablename = 'vehicles'
    ) THEN
        CREATE POLICY "Vehicles are publicly readable" ON vehicles FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Users can read their own rentals' AND tablename = 'rentals'
    ) THEN
        CREATE POLICY "Users can read their own rentals" ON rentals FOR SELECT USING (auth.uid() = user_id);
    END IF;
END $$;
-- (No INSERT/UPDATE/DELETE policies: writes are only possible through the server's service-role key.)
